---
title: "Data Transformation"
author: "Erich Robbi"
date: "2022-11-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the libraries

```{r}
library(affy)
library(limma)
library(annotate)
library(hgu133plus2.db)
library(biomaRt)
library(tidyverse)
library(GEOquery)
```

We use the RMA normalization, which performs:
- background correction
- normalization
- expression calculation

```{r}
files = list.files("../data/", full.names = TRUE)
data = ReadAffy(filenames = files)

# Perform RMA normalization
rma.data <- rma(data)
rm(data)

# Get the expression estimates
expression.matrix <- exprs(rma.data)
rm(rma.data)

expression.backup <- expression.matrix
nomi_colonne <- colnames(expression.matrix)
expression.matrix <- t(expression.matrix)
expression.matrix <- as_tibble(expression.matrix)
expression.matrix$sample_names <- nomi_colonne
write.csv(expression.matrix,"./exp_matrix.csv", row.names = FALSE)
write.csv(expression.matrix,"./exp_matrix_rows.csv", row.names = T)
#expression.matrix <- as_tibble(t(expression.matrix))
#write_csv2(expression.matrix,"../matrice.csv")
```

Get the dataset metadata
```{r}
x <- GEOquery::getGEO(filename='GSE10810_series_matrix.txt')
x@phenoData@data[["title"]]
x@phenoData@data[["geo_accession"]]
```


```{r}
gene.set.of.interest <- c("SNORA1","SNORA12","SNORA14B","SNORA16A","SNORA21","SNORA23","SNORA24","SNORA32","SNORA38","SNORA44","SNORA48","SNORA49","SNORA52","SNORA53","SNORA57","SNORA61","SNORA63","SNORA64","SNORA65","SNORA70","SNORA71C","SNORA73A","SNORA73B","SNORA75","SNORA78","SNORA8","SNORD10","SNORD102","SNORD104","SNORD105","SNORD105B","SNORD108","SNORD110","SNORD111B","SNORD113-3","SNORD113-4","SNORD114-1","SNORD114-13","SNORD114-14","SNORD114-19","SNORD114-20","SNORD114-21","SNORD115-23","SNORD115-32","SNORD116-13","SNORD119","SNORD12","SNORD12B","SNORD13","SNORD14A","SNORD14C","SNORD14D","SNORD15B","SNORD16","SNORD17","SNORD18A","SNORD1B","SNORD20","SNORD22","SNORD26","SNORD28","SNORD29","SNORD32A","SNORD33","SNORD34","SNORD35A","SNORD36A","SNORD36B","SNORD38A","SNORD3A","SNORD3D","SNORD41","SNORD42A","SNORD42B","SNORD44","SNORD45A","SNORD47","SNORD49B","SNORD4B","SNORD5","SNORD50A","SNORD52","SNORD53","SNORD54","SNORD55","SNORD56","SNORD57","SNORD58A","SNORD58C","SNORD59A","SNORD60","SNORD63","SNORD64","SNORD65","SNORD68","SNORD69","SNORD71","SNORD74","SNORD76","SNORD8","SNORD81","SNORD82","SNORD84","SNORD86","SNORD87","SNORD89","SNORD94","SNORD96A","SNORD97","SNORD99","TMX1","ZFAS1","CDKN2B-AS1","CWF19L1","EIF4A1","EP400","HIF1A-AS2","MEG8","NOP56","RACK1","RPL13A","RPS13","SCARNA12","SNHG12","SNHG20","SNHG5","SNHG6","SNHG7","SNHG8","AP1G1","CFDP1","CHD8","DDX39B","EEF2","EIF4A2","EIF4G2","GAS5","GNL3","HSPA8","HSPA9","IPO7","MYRIP","NAN","NCL","NFATC3","PCAT4","PPAN","PRKAA1","PRRC2A","PTCD3","RABGGTB","RNF149","RPL10","RPL12","RPL13","RPL17","RPL21","RPL23","RPL23A","RPL4","RPL7A","RPLP2","RPS11","RPS2","RPS20","RPS3","RPS8","SF3B3","SLC25A3","SNHG1","SNHG3","SNHG9","SNORD1C","SNORD35B","SNORD37","SNRPB","SNX5","TAF1D","TNPO2","TOMM20","WDR43")
```


```{r}
exp_tib <- as_tibble(expression.backup)
exp_tib$GSM1045191_N1_15_12_04.CEL
```

```{r}
expression.matrix[expression.matrix$sample_names ==  'GSM1045191_N1_15_12_04.CEL', ]
```

```{r}
gse <- getGEO(filename="GSE61304_series_matrix.txt",GSEMatrix = TRUE,getGPL = FALSE) #Retrieve matrix data and store it in R object
show(object = gse) ## To summarize the gse object
x <- gse$`Stage:ch1` #Get expression set from gse object

write.csv(x = x, file = "GSE2553.expression.matrix.csv", quote = F, row.names = F)
```

