```{r}
BiocManager::install("maEndToEnd")
suppressPackageStartupMessages({library("maEndToEnd")})
suppressPackageStartupMessages({library('affy')})
```

```{r}
files <- list.files("../data/", full.names = TRUE)
data <- ReadAffy(filenames = files)
data <- read.csv("expr_new.csv")
data <- data[ , !(names(data) %in% c('X'))]
```

```{r fig.width=15}
data_no_extra <- data[ , !(names(data) %in% c('X', 'type', 'diagnosis', 'sample', 'source'))]
PCA_raw <- prcomp(t(log2(data_no_extra)), scale. = FALSE)

percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])

dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2])

ggplot(dataGG, aes(PC1, PC2)) +
       geom_point(aes(shape = data$diagnosis, colour = data$type)) +
  ggtitle("PCA plot of the log-transformed raw expression data") +
  xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
  ylab(paste0("PC2, VarExp: ", percentVar[2], "%")) +
  theme(plot.title = element_text(hjust = 0.5))+
  coord_fixed(ratio = sd_ratio) +
  scale_shape_manual(values = c(4,15)) +
  scale_color_manual(values = c("darkorange2", "dodgerblue4"))
```

